/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "GestorJuegos.h"

typedef struct
{
	int Codigo;
	char Tablero[9][9];
	TDificultad Dificultad;
} TJuego;

TJuego *Sudokus=NULL;
int NSudokus=0;


void generarSudoku(TJuego *Sudoku){
	
	srand(time(NULL));

	for(int i=0;i<9;i++){
		for(int j=0;j<9;j++){
	Sudoku->Tablero[i][j]='';
		}
	}

	rellenarSudoku(Sudoku->Tablero,0,0);
}

bool rellenarSudoku(char sudoku[9][9], int fila, int columna){

	if(fila==9){
		return true;	
	}
	if(columna == 9){
		return rellenarSudoku(sudoku,fila+1,0);
	}
	if(sudoku[fila][columna] != ''){
		return rellenarSudoku(sudoku,fila,columna+1);
	}

	for(char numero='1';numero <='9';numero++){
		if(numeroSeguro(sudoku,fila,columna,numero)){
			sudoku[fila][columna] = numero;
			
			if(rellenarSudoku(sudoku,fila,columna+1)){
				return true;
			}
			sudoku[fila][columna] = ''; 
		}
	}
	
	
	return false;
}

bool numeroSeguro(char sudoku[9][9], int fila, int columna, char numero){

    for (int i = 0; i < 9; i++) {
        if (sudoku[fila][columna] == numero) {
            return false;
        }
    }


    for (int i = 0; i < 9; i++) {
        if (sudoku[fila][columna] == numero) {
            return false;
        }
    }


    int startRow = fila - (fila % 3);
    int startCol = columna - (columna % 3);
    for (int i = 0; i < 3; i++) {
        for (int j = 0; j < 3; j++) {
            if (sudoku[startRow + i][startCol + j] == numero) {
                return false;
            }
        }
    }

    return true;  

}

int *
nuevo_1_svc(TDificultad *argp, struct svc_req *rqstp)
{
	static int  result;
	if(NSudokus==0){

	Sudokus = (TJuego*)malloc(sizeof(TJuego));
	Sudokus[0].Codigo = 1;
	Sudokus[0].Dificultad = argp;
	result = 1;
	rellenarSudoku(Sudokus[0]); hay que cambiar esta funcion un poco

	}else{
	y terminar esta
	Sudokus = (TJuego*)realloc(Sudokus,sizeof(TJuego)*(NSudokus+1));
	
	}
	

	
	NSudokus++;
	return &result;
}

bool_t *
borrar_1_svc(int *argp, struct svc_req *rqstp)
{
	static bool_t  result;
	
	result = false;
	if(argp > NSudokus){ //si es mayor que el numero de sudokus no es ninguno de los que existen
		for (int i = argp; i < Sudokus - 1; i++)
		    contacts[i] = contacts[i+1];
		Sudokus = (TJuego*)realloc(Sudokus,sizeof(TJuego)*(NSudokus-1));
		NSudokus--;
		result = true;
	}

	return &result;
}

bool_t *
ponervalor_1_svc(TFCV *argp, struct svc_req *rqstp)
{
	static bool_t  result;
	result = false;
	if( !(argp->pCod > NSudokus || argp->pFil > 9 || argp->pFil < 1 || argp->pCol > 9 
|| argp->pCol < 1 || argp->pVal > 9 || argp->pVal < 1)){
		
	Sudokus[argp->pCod].Tablero[argp->pFil][argp->pCol] = argp->pVal;
	result = true;
	}
	return &result;
}

char *
obtenervalor_1_svc(TFC *argp, struct svc_req *rqstp)
{
	static char  result;
	result = '-';	
	if(!(argp->pCod > NSudokus)){
	result = Sudokus[argp->pCod].Tablero[argp->pFil][argp->pCol];
	}
	return &result;
}

bool_t *
comprobarvalor_1_svc(TFCV *argp, struct svc_req *rqstp)
{
	static bool_t  result;
	

	result = false;
	if(!(argp->pCod > NSudokus)){
		
	}

	return &result;
}

int *
numerohuecos_1_svc(int *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

bool_t *
correcto_1_svc(int *argp, struct svc_req *rqstp)
{
	static bool_t  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RCadena *
ayuda_1_svc(TFC *argp, struct svc_req *rqstp)
{
	static RCadena  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RCadena *
getsudoku_1_svc(int *argp, struct svc_req *rqstp)
{
	static RCadena  result;

	/*
	 * insert server code here
	 */

	return &result;
}
