/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "GestorBiblioteca.h"

#include <ctype.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>

#define Cls system("clear")
#define Pause                                                                  \
    system("read -p \"\nPulsa la tecla return para continuar..... \" a")

#define MostrarAviso(Texto)                                                    \
    {                                                                          \
        printf(Texto);                                                         \
        Pause;                                                                 \
    }

int MenuPrincipal() {
    int Salida;
    do {
        Cls;
        printf(" GESTOR BIBLIOTECARIO 1.0 (M. PRINCIPAL)\n");
        printf("*****************************************\n");
        printf("\t1.- M. Administración\n");
        printf("\t2.- Consulta de libros\n");
        printf("\t3.- Préstamo de libros\n");
        printf("\t4.- Devolución de libros\n");
        printf("\t0.- Salir\n\n");
        printf(" Elige opción: ");
        scanf("%d", &Salida);
        if (Salida < 0 || Salida > 4)
            MostrarAviso("\n\n *** Error en la entrada de Datos.***\n\n");
    } while (Salida < 0 || Salida > 4);
    return Salida;
}

int MenuAdministracion() {
    int Salida;
    do {
        Cls;
        printf(" GESTOR BIBLIOTECARIO 1.0 (M. ADMINISTRACION)\n");
        printf("**********************************************\n");
        printf("\t1.- Cargar datos Biblioteca\n");
        printf("\t2.- Guardar datos Biblioteca\n");
        printf("\t3.- Nuevo libro\n");
        printf("\t4.- Comprar libros\n");
        printf("\t5.- Retirar libros\n");
        printf("\t6.- Ordenar libros\n");
        printf("\t7.- Buscar libros\n");
        printf("\t8.- Listar libros\n");
        printf("\t0.- Salir\n\n");
        printf(" Elige opción: ");
        scanf("%d", &Salida);
        if (Salida < 0 || Salida > 8)
            MostrarAviso("\n\n *** Error en la entrada de Datos.***\n\n");
    } while (Salida < 0 || Salida > 8);
    return Salida;
}

void Formatea(char *Salida, const char *p, int ancho, char Caracter) {
    Cadena vacia;
    int len = ancho - strlen(p);
    int l = 0, c = 0;

    while (p[l] != '\0') {
        if ((unsigned char)p[l] > 128)
            c++;
        l++;
    }
    len += c / 2;

    if (len < 0)
        len = 0;
    for (int i = 0; i < len; i++)
        vacia[i] = Caracter;
    vacia[len] = '\0';

    sprintf(Salida, "%s%s", p, vacia);
}

void MostrarLibro(TLibro *L, int Pos, bool_t Cabecera) {
    Cadena T, A, B, PI;
    if (Cabecera == TRUE) {
        printf("%-*s%-*s%-*s%*s%*s%*s\n", 5, "POS", 58, "TITULO", 18, "ISBN", 4,
               "DIS", 4, "PRE", 4, "RES");
        printf("     %-*s%-*s%-*s\n", 30, "AUTOR", 28, "PAIS (IDIOMA)", 12,
               "AÑO");
        Formatea(B, "*", 93, '*');
        printf("%s\n", B);
    }
    Formatea(T, L->Titulo, 58, ' ');
    Formatea(A, L->Autor, 30, ' ');
    strcpy(B, L->Pais);
    strcat(B, " (");
    strcat(B, L->Idioma);
    strcat(B, ")");
    Formatea(PI, B, 28, ' ');
    printf("%-5d%s%-*s%*d%*d%*d\n", Pos + 1, T, 18, L->Isbn, 4, L->NoLibros, 4,
           L->NoPrestados, 4, L->NoListaEspera);
    printf("     %s%s%-*d\n", A, PI, 12, L->Anio);
}

void gestorbiblioteca_1(char *host) {
    CLIENT *clnt;
    int *result_1;
    char conexion_1_arg;
    bool_t *result_2;
    int desconexion_1_arg;
    int *result_3;
    TConsulta cargardatos_1_arg;
    bool_t *result_4;
    int guardardatos_1_arg;
    int *result_5;
    TNuevo nuevolibro_1_arg;
    int *result_6;
    TComRet comprar_1_arg;
    int *result_7;
    TComRet retirar_1_arg;
    bool_t *result_8;
    TOrdenacion ordenar_1_arg;
    int *result_9;
    int nlibros_1_arg;
    int *result_10;
    TConsulta buscar_1_arg;
    TLibro *result_11;
    TPosicion descargar_1_arg;
    int *result_12;
    TPosicion prestar_1_arg;
    int *result_13;
    TPosicion devolver_1_arg;

#ifndef DEBUG
    clnt = clnt_create(host, GESTORBIBLIOTECA, GESTORBIBLIOTECA_VER, "udp");
    if (clnt == NULL) {
        clnt_pcreateerror(host);
        exit(1);
    }
#endif /* DEBUG */

    result_1 = conexion_1(&conexion_1_arg, clnt);
    if (result_1 == (int *)NULL) {
        clnt_perror(clnt, "call failed");
    }
    result_2 = desconexion_1(&desconexion_1_arg, clnt);
    if (result_2 == (bool_t *)NULL) {
        clnt_perror(clnt, "call failed");
    }
    result_3 = cargardatos_1(&cargardatos_1_arg, clnt);
    if (result_3 == (int *)NULL) {
        clnt_perror(clnt, "call failed");
    }
    result_4 = guardardatos_1(&guardardatos_1_arg, clnt);
    if (result_4 == (bool_t *)NULL) {
        clnt_perror(clnt, "call failed");
    }
    result_5 = nuevolibro_1(&nuevolibro_1_arg, clnt);
    if (result_5 == (int *)NULL) {
        clnt_perror(clnt, "call failed");
    }
    result_6 = comprar_1(&comprar_1_arg, clnt);
    if (result_6 == (int *)NULL) {
        clnt_perror(clnt, "call failed");
    }
    result_7 = retirar_1(&retirar_1_arg, clnt);
    if (result_7 == (int *)NULL) {
        clnt_perror(clnt, "call failed");
    }
    result_8 = ordenar_1(&ordenar_1_arg, clnt);
    if (result_8 == (bool_t *)NULL) {
        clnt_perror(clnt, "call failed");
    }
    result_9 = nlibros_1(&nlibros_1_arg, clnt);
    if (result_9 == (int *)NULL) {
        clnt_perror(clnt, "call failed");
    }
    result_10 = buscar_1(&buscar_1_arg, clnt);
    if (result_10 == (int *)NULL) {
        clnt_perror(clnt, "call failed");
    }
    result_11 = descargar_1(&descargar_1_arg, clnt);
    if (result_11 == (TLibro *)NULL) {
        clnt_perror(clnt, "call failed");
    }
    result_12 = prestar_1(&prestar_1_arg, clnt);
    if (result_12 == (int *)NULL) {
        clnt_perror(clnt, "call failed");
    }
    result_13 = devolver_1(&devolver_1_arg, clnt);
    if (result_13 == (int *)NULL) {
        clnt_perror(clnt, "call failed");
    }
#ifndef DEBUG
    clnt_destroy(clnt);
#endif /* DEBUG */
}

void cargarFichero(int idAdmin, CLIENT *clnt) {
    int cargado = -1;
    TConsulta tmp;
    // Cadena nomFichero = "Biblioteca.cdat";
    Cadena nomFichero = "";
    printf("\nIntroduce el nombre del fichero de datos: ");
    scanf("%s", nomFichero);
    // printf("\nMetemos de forma automatica %s", nomFichero);
    strcpy(tmp.Datos, nomFichero);

    tmp.Ida = idAdmin;
    cargado = *cargardatos_1(&tmp, clnt);
    if (cargado == 1) {
        printf("\nSe ha cargado correctamente el fichero\n");
    } else if (cargado == -1) {
        printf("\nEl fichero no se ha cargado "
               "correctamente porque ya hay un admin dado "
               "de alta o el enviado no es correcto\n");
    } else if (cargado == 0) {
        printf("\nEl fichero no se ha cargado correctamente "
               "porque ha habido un error de tratamiento de "
               "fichero o de memoria dinamica\n");
    }
    Pause;
}

void añadirNuevoLibro(int idAdmin, CLIENT *clnt) {
    TNuevo nuevoLibro;
    int resultadoNuevoLibro;
    printf("\nIntroduce el Isbn: ");
    scanf("%s", nuevoLibro.Libro.Isbn);
    printf("\nIntroduce el Autor: ");
    scanf("%s", nuevoLibro.Libro.Autor);
    printf("\nIntroduce el Titulo: ");
    scanf("%s", nuevoLibro.Libro.Titulo);
    printf("\nIntroduce el año: ");
    scanf("%d", &nuevoLibro.Libro.Anio);
    printf("\nIntroduce el Pais: ");
    scanf("%s", nuevoLibro.Libro.Pais);
    printf("\nIntroduce el Idioma: ");
    scanf("%s", nuevoLibro.Libro.Idioma);
    printf("\nIntroduce el Numero de libros inicial: ");
    scanf("%d", &nuevoLibro.Libro.NoLibros);
    if (nuevoLibro.Libro.NoLibros >= 0) {
        nuevoLibro.Libro.NoListaEspera = 0;
        nuevoLibro.Libro.NoPrestados = 0;
        nuevoLibro.Ida = idAdmin;
        resultadoNuevoLibro = *nuevolibro_1(&nuevoLibro, clnt);
        if (resultadoNuevoLibro == 1) {
            MostrarAviso("\n*** El libro ha sido añadido "
                         "correctamente.**\n");
        } else {
            MostrarAviso("\nError con el libro a introducir\n");
        }
    } else {
        MostrarAviso("\nNo pude haber un numero incial de libros negativo\n");
    }
}

void comprarNuevosLibros(int idAdmin, CLIENT *clnt) {
    TPosicion busquedaConFiltro;
    TLibro mostrar;
    int nLibros;
    Cadena B2;
    TComRet compLibros;
    int resultadoComprarLibros;
    busquedaConFiltro.Ida = idAdmin;
    busquedaConFiltro.Pos = 0;
    nLibros = *nlibros_1(&idAdmin, clnt);
    compLibros.Ida = idAdmin;
    printf("\nIntroduce el ISBN del libro al que quieres "
           "añadir ejemplares: ");
    scanf("%s", compLibros.Isbn);

    printf("%-*s%-*s%-*s%*s%*s%*s\n", 5, "POS", 58, "TITULO", 18, "ISBN", 4,
           "DIS", 4, "PRE", 4, "RES");
    printf("     %-*s%-*s%-*s\n", 30, "AUTOR", 28, "PAIS (IDIOMA)", 12, "AÑO");
    Formatea(B2, "*", 93, '*');
    printf("%s\n", B2);
    for (int i = 0; i < nLibros; ++i) {
        mostrar = *descargar_1(&busquedaConFiltro, clnt);
        busquedaConFiltro.Pos++;
        if (strstr(mostrar.Isbn, compLibros.Isbn) != NULL) {
            if (mostrar.Anio != -1 && strcmp(mostrar.Titulo, "????") != 0)
                MostrarLibro(&mostrar, i, FALSE);
            else {
                MostrarAviso("\nError, el libro no existe, "
                             "posicion erroena enviada\n");
            }
        }
    }
    printf("\nIntroduce el numero de libros que quieres "
           "añadir: ");
    scanf("%d", &compLibros.NoLibros);
    if (compLibros.NoLibros >= 0) {
        resultadoComprarLibros = *comprar_1(&compLibros, clnt);
        if (resultadoComprarLibros == 1) {
            MostrarAviso("\nTodo correcto\n");
        } else if (resultadoComprarLibros == 0) {
            MostrarAviso("\nNo hay ningun libro con dicho ISBN\n");
        } else if (resultadoComprarLibros == -1) {
            MostrarAviso("\nIdAdmin administrado erroneo o ya "
                         "hay otro admin\n");
        } else {
            MostrarAviso("\nTodo correcto, se han añadido "
                         "los libros\n");
        }
    } else {
        MostrarAviso("\nNo puedes añadir un numero negativo de libros\n");
    }
}
void retirarLibros(int idAdmin, CLIENT *clnt) {
    TComRet retLibros;
    Cadena B2;
    int resultadoRetirarLibros;
    TPosicion busquedaConFiltro;
    TLibro mostrar;
    int nLibros;
    nLibros = *nlibros_1(&idAdmin, clnt);
    retLibros.Ida = idAdmin;
    busquedaConFiltro.Ida = idAdmin;
    busquedaConFiltro.Pos = 0;

    printf("\nIntroduce el ISBN del libro al que quieres "
           "retirar ejemplares: ");
    scanf("%s", retLibros.Isbn);

    printf("%-*s%-*s%-*s%*s%*s%*s\n", 5, "POS", 58, "TITULO", 18, "ISBN", 4,
           "DIS", 4, "PRE", 4, "RES");
    printf("     %-*s%-*s%-*s\n", 30, "AUTOR", 28, "PAIS (IDIOMA)", 12, "AÑO");
    Formatea(B2, "*", 93, '*');
    printf("%s\n", B2);
    for (int i = 0; i < nLibros; ++i) {
        mostrar = *descargar_1(&busquedaConFiltro, clnt);
        busquedaConFiltro.Pos++;
        if (strstr(mostrar.Isbn, retLibros.Isbn) != NULL) {
            if (mostrar.Anio != -1 && strcmp(mostrar.Titulo, "????") != 0)
                MostrarLibro(&mostrar, i, FALSE);
            else {
                MostrarAviso("\nError, el libro no existe, "
                             "posicion erroena enviada\n");
            }
        }
    }
    printf("\nIntroduce el numero de libros que quieres "
           "retirar: ");
    scanf("%d", &retLibros.NoLibros);
    if (retLibros.NoLibros >= 0) {
        resultadoRetirarLibros = *retirar_1(&retLibros, clnt);
        if (resultadoRetirarLibros == 1) {
            MostrarAviso("\nTodo correcto\n");
        } else if (resultadoRetirarLibros == 0) {
            MostrarAviso("\nNo hay ningun libro con dicho ISBN\n");
        } else if (resultadoRetirarLibros == -1) {
            MostrarAviso("\nIdAdmin administrado erroneo o ya "
                         "hay otro admin\n");
        } else {
            MostrarAviso("\nError: no hay suficientes libros para retirar\n");
        }
    } else {
        MostrarAviso("\nNo puedes retirar menos de 0 libros\n");
    }
}

void ordenarLibros(int idAdmin, CLIENT *clnt) {
    TOrdenacion opcionCampo;
    opcionCampo.Ida = idAdmin;
    printf("\nElige código de ordenacion\n0.- Por "
           "Isbn\n1.- Por Título\n2.- Por Autor\n3.- Por "
           "Año\n4.- Por País\n5.- Por Idioma\n6.- Por nº "
           "de libros Disponibles\n7.- Por nº de libros "
           "Prestados\n8.- Por nº de libros en espera "
           "\n\nElige una opcion: ");
    scanf("%d", &opcionCampo.Campo);
    if (opcionCampo.Campo >= 0 || opcionCampo.Campo < 8) {
        if (*ordenar_1(&opcionCampo, clnt)) {
        } else {
            MostrarAviso("\nError al ordenar\n");
        }
    } else {
        MostrarAviso("\nNo es una opcion\n");
    }
}

void busquedaConFiltro(int idAdmin, CLIENT *clnt) {
    TPosicion busquedaConFiltro;
    busquedaConFiltro.Ida = idAdmin;
    busquedaConFiltro.Pos = 0;
    char filtro;
    TLibro mostrar;
    Cadena texto;
    int nLibros;
    printf("\nIntroduce el texto a buscar: ");
    scanf("%s", texto);
    __fpurge(stdin);
    printf("\nCódigo de busqueda:\nI.- Por ISBN\nT.- Por "
           "Titulo\nA.- Por Autor\nP.- Por País\nD.- Por "
           "Idioma\n*.- Por todos los campos.\n\nIntroduce "
           "Código: ");
    scanf("%c", &filtro);
    __fpurge(stdin);
    nLibros = *nlibros_1(&idAdmin, clnt);
    Cadena B2;
    printf("%-*s%-*s%-*s%*s%*s%*s\n", 5, "POS", 58, "TITULO", 18, "ISBN", 4,
           "DIS", 4, "PRE", 4, "RES");
    printf("     %-*s%-*s%-*s\n", 30, "AUTOR", 28, "PAIS (IDIOMA)", 12, "AÑO");
    Formatea(B2, "*", 93, '*');
    printf("%s\n", B2);
    switch (filtro) {
    case 'I':
        for (int i = 0; i < nLibros; ++i) {
            mostrar = *descargar_1(&busquedaConFiltro, clnt);
            busquedaConFiltro.Pos++;
            if (strstr(mostrar.Isbn, texto) != NULL) {
                if (mostrar.Anio != -1 && strcmp(mostrar.Titulo, "????") != 0)
                    MostrarLibro(&mostrar, i, FALSE);
                else {
                    MostrarAviso("\nError, el libro no existe, "
                                 "posicion erroena enviada\n");
                }
            }
        }
        break;
    case 'T':
        for (int i = 0; i < nLibros; ++i) {
            mostrar = *descargar_1(&busquedaConFiltro, clnt);
            busquedaConFiltro.Pos++;
            if (strstr(mostrar.Titulo, texto) != NULL) {
                if (mostrar.Anio != -1 && strcmp(mostrar.Autor, "????") != 0)
                    MostrarLibro(&mostrar, i, FALSE);
                else {
                    MostrarAviso("\nError, el libro no existe, "
                                 "posicion erroena enviada\n");
                }
            }
        }
        break;
    case 'A':
        for (int i = 0; i < nLibros; ++i) {
            mostrar = *descargar_1(&busquedaConFiltro, clnt);
            busquedaConFiltro.Pos++;
            if (strstr(mostrar.Autor, texto) != NULL) {
                if (mostrar.Anio != -1 && strcmp(mostrar.Autor, "????") != 0)
                    MostrarLibro(&mostrar, i, FALSE);
                else {
                    MostrarAviso("\nError, el libro no existe, "
                                 "posicion erroena enviada\n");
                }
            }
        }
        break;
    case 'P':
        for (int i = 0; i < nLibros; ++i) {
            mostrar = *descargar_1(&busquedaConFiltro, clnt);
            busquedaConFiltro.Pos++;
            if (strstr(mostrar.Pais, texto) != NULL) {
                if (mostrar.Anio != -1 && strcmp(mostrar.Autor, "????") != 0)
                    MostrarLibro(&mostrar, i, FALSE);
                else {
                    MostrarAviso("\nError, el libro no existe, "
                                 "posicion erroena enviada\n");
                }
            }
        }
        break;
    case 'D':
        for (int i = 0; i < nLibros; ++i) {
            mostrar = *descargar_1(&busquedaConFiltro, clnt);
            busquedaConFiltro.Pos++;
            if (strstr(mostrar.Idioma, texto) != NULL) {
                if (mostrar.Anio != -1 && strcmp(mostrar.Autor, "????") != 0)
                    MostrarLibro(&mostrar, i, FALSE);
                else {
                    MostrarAviso("\nError, el libro no existe, "
                                 "posicion erroena enviada\n");
                }
            }
        }
        break;
    case '*':
        for (int i = 0; i < nLibros; ++i) {
            mostrar = *descargar_1(&busquedaConFiltro, clnt);
            busquedaConFiltro.Pos++;
            if (strstr(mostrar.Titulo, texto) != NULL ||
                strstr(mostrar.Autor, texto) != NULL ||
                strstr(mostrar.Idioma, texto) != NULL ||
                strstr(mostrar.Isbn, texto) != NULL ||
                strstr(mostrar.Pais, texto) != NULL) {
                if (mostrar.Anio != -1 && strcmp(mostrar.Autor, "????") != 0)
                    MostrarLibro(&mostrar, i, FALSE);
                else {
                    MostrarAviso("\nError, el libro no existe, "
                                 "posicion erroena enviada\n");
                }
            }
        }
        break;

    default:
        MostrarAviso("\nError, no es filtro valido\n");
        break;
    }
    Pause;
}

void mostrarTodosLibros(int idAdmin, CLIENT *clnt) {
    TPosicion todosLibros;
    TLibro libro;
    todosLibros.Ida = idAdmin;
    todosLibros.Pos = 0;
    int nLibrosTodos;
    nLibrosTodos = *nlibros_1(&idAdmin, clnt);
    libro = *descargar_1(&todosLibros, clnt);
    Cadena T, A, B, PI;
    printf("%-*s%-*s%-*s%*s%*s%*s\n", 5, "POS", 58, "TITULO", 18, "ISBN", 4,
           "DIS", 4, "PRE", 4, "RES");
    printf("     %-*s%-*s%-*s\n", 30, "AUTOR", 28, "PAIS (IDIOMA)", 12, "AÑO");
    Formatea(B, "*", 93, '*');
    printf("%s\n", B);
    for (int i = 0; i < nLibrosTodos; ++i) {
        libro = *descargar_1(&todosLibros, clnt);
        todosLibros.Pos++;
        if (libro.Anio != -1 && strcmp(libro.Autor, "????") != 0)
            MostrarLibro(&libro, i, FALSE);
        else {
            MostrarAviso("\nError, el libro no existe, "
                         "posicion erroena enviada\n");
        }
    }
    Pause;
}

void busquedaPorISBN(int idAdmin, CLIENT *clnt) {
    TPosicion busquedaConFiltroDevolver;
    TLibro mostrarDevolver;
    int nLibrosDevolver;
    Cadena isbn;
    Cadena B2;
    busquedaConFiltroDevolver.Ida = idAdmin;
    busquedaConFiltroDevolver.Pos = 0;

    printf("\nIntroduce el ISBN del libro a devolver: ");
    scanf("%s", isbn);
    __fpurge(stdin);
    nLibrosDevolver = *nlibros_1(&idAdmin, clnt);
    printf("%-*s%-*s%-*s%*s%*s%*s\n", 5, "POS", 58, "TITULO", 18, "ISBN", 4,
           "DIS", 4, "PRE", 4, "RES");
    printf("     %-*s%-*s%-*s\n", 30, "AUTOR", 28, "PAIS (IDIOMA)", 12, "AÑO");
    Formatea(B2, "*", 93, '*');
    printf("%s\n", B2);

    for (int i = 0; i < nLibrosDevolver; ++i) {
        mostrarDevolver = *descargar_1(&busquedaConFiltroDevolver, clnt);
        busquedaConFiltroDevolver.Pos++;
        if (strstr(mostrarDevolver.Isbn, isbn) != NULL) {
            if (mostrarDevolver.Anio != -1 &&
                strcmp(mostrarDevolver.Titulo, "????") != 0)
                MostrarLibro(&mostrarDevolver, i, FALSE);
            else {
                MostrarAviso("\nError, el libro no existe, "
                             "posicion erroena enviada\n");
            }
        }
    }
}

int main(int argc, char *argv[]) {
    char *host;

    if (argc < 2) {
        printf("usage: %s server_host\n", argv[0]);
        exit(1);
    }
    host = argv[1];
    // gestorbiblioteca_1 (host);
    CLIENT *clnt;

    int opcMenuPrincipal, opcMenuAdmin, idAdmin = -1;
    Cadena contraseña = "";
    clnt = clnt_create(host, GESTORBIBLIOTECA, GESTORBIBLIOTECA_VER, "tcp");
    if (clnt == NULL) {
        clnt_pcreateerror(host);
        printf("Host no encontrado, saliendo");
        exit(1);
    }
    printf("\nCliente: Tengo conexion, comenzamos\n");
    do {
        opcMenuPrincipal = MenuPrincipal();
        switch (opcMenuPrincipal) {
        case 1:
            Cls;
            printf("\nPor favor inserte la contraseña de administracion: ");
            scanf("%s", contraseña);
            idAdmin = *conexion_1(contraseña, clnt);
            printf("\nTenemos de idAdmin %d\n", idAdmin);
            if (idAdmin == -1) {
                MostrarAviso("\nCliente: Error, ya hay un admin activo\n");
            } else if (idAdmin == -2) {
                MostrarAviso("\nCliente: Error, contraseña equivocada\n");
            } else {
                printf(
                    "\nCliente: Todo OK, hemos iniciado sesion con el ID %d\n",
                    idAdmin);
                Pause;
                do {

                    opcMenuAdmin = MenuAdministracion();
                    switch (opcMenuAdmin) {
                    case 1:

                        cargarFichero(idAdmin, clnt);

                        break;
                    case 2:

                        if (guardardatos_1(&idAdmin, clnt)) {
                            MostrarAviso("\nSe ha guardado correctamente\n");
                        } else {
                            MostrarAviso("\nHa ocurrido un error al guardar el "
                                         "fichero\n");
                        }

                        break;
                    case 3:
                        añadirNuevoLibro(idAdmin, clnt);
                        break;
                    case 4:
                        comprarNuevosLibros(idAdmin, clnt);
                        break;
                    case 5:
                        retirarLibros(idAdmin, clnt);
                        break;
                    case 6:
                        ordenarLibros(idAdmin, clnt);
                        break;
                    case 7:
                        busquedaConFiltro(idAdmin, clnt);
                        break;
                    case 8:
                        mostrarTodosLibros(idAdmin, clnt);
                        break;

                    default:
                        break;
                    }
                } while (opcMenuAdmin != 0);
                bool_t desconectar = *desconexion_1(&idAdmin, clnt);
                if (desconectar == TRUE) {
                    MostrarAviso("\nSe desconecta de forma correcta\n");
                } else {
                    MostrarAviso(
                        "\nHa habido un error en la desconexion del admin\n");
                }
                idAdmin = -1;
            }
            break;
        case 2:
            busquedaConFiltro(idAdmin, clnt);
            break;
        case 3:
            busquedaConFiltro(idAdmin, clnt);
            char sino;
            TPosicion posSacar;
            posSacar.Ida = idAdmin;
            printf("\n¿Quiere sacar algun libro? (s/n)?: ");
            scanf("%c", &sino);
            __fpurge(stdin);
            if (sino == 's' || sino == 'S') {
                printf("\nIndique la posicion del libro a sacar: ");
                scanf("%d", &posSacar.Pos);
                int resultado = *prestar_1(&posSacar, clnt);
                if (resultado == 1) {
                    MostrarAviso("\nTodo ok\n");
                } else if (resultado == 0) {
                    MostrarAviso("\nSe pone en lista de espera\n");
                } else {
                    MostrarAviso("\nError con el prestamos\n");
                }
            } else {
                MostrarAviso("\nEntonces terminamos\n");
            }

            break;
        case 4:
            busquedaPorISBN(idAdmin, clnt);
            TPosicion devolviendo;
            devolviendo.Ida = idAdmin;
            char sinoDevolver;
            printf("\n¿Quiere devolver algun libro a la biblioteca? (S/n): ");
            scanf("%c", &sinoDevolver);
            __fpurge(stdin);
            if (sinoDevolver == 's' || sinoDevolver == 'S') {
                printf("\nIndoque la posicion del libro a devolver: ");
                scanf("%d", &devolviendo.Pos);
                int resultado = *devolver_1(&devolviendo, clnt);
                if (resultado == 0) {
                    MostrarAviso("\nTodo ok\n");
                } else if (resultado == 1) {
                    MostrarAviso("\nSe reducen los esperados\n");
                } else if (resultado == 2) {
                    MostrarAviso("\nError con la devolucion, no hay nada que "
                                 "devolver\n");
                } else {
                    MostrarAviso("\nPosicion incorrecta\n");
                }
            } else {
                MostrarAviso("\nEntonces hemos terminado\n");
            }
            break;

        default:
            break;
        }

    } while (opcMenuPrincipal != 0);
    printf("\nCliente: hemos terminado, adios\n");

    exit(0);
}
