/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author marin
 */
public class VistaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VistaPrincipal
     */
    public VistaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        OPCAleatorio = new javax.swing.JButton();
        OPCFichero = new javax.swing.JButton();
        BotonTodosAleatorios = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(2000, 1000));
        setMinimumSize(new java.awt.Dimension(900, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 153));
        jLabel1.setText("Bienvenid@ a ISMAMI ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 153));
        jLabel2.setText("Analizador de algoritmos");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 452, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("¿Cómo desea realizar este análisis?");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 220, 317, -1));

        OPCAleatorio.setText("Análisis de un algoritmo");
        OPCAleatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OPCAleatorioActionPerformed(evt);
            }
        });
        getContentPane().add(OPCAleatorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 370, -1, -1));

        OPCFichero.setText("Análisis de un fichero existente");
        OPCFichero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OPCFicheroActionPerformed(evt);
            }
        });
        getContentPane().add(OPCFichero, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 380, -1, -1));

        BotonTodosAleatorios.setText("Comparación de todos los algoritmos");
        getContentPane().add(BotonTodosAleatorios, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 430, 240, -1));

        jLabel4.setText("Análisis sobre puntos aleatorios");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OPCAleatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OPCAleatorioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OPCAleatorioActionPerformed

    private void OPCFicheroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OPCFicheroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OPCFicheroActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton BotonTodosAleatorios;
    public javax.swing.JButton OPCAleatorio;
    public javax.swing.JButton OPCFichero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
