/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import Controlador.ControlaPuntos;
import Modelo.Punto;
import java.awt.Font;
import java.awt.Graphics;
import java.io.File;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.xml.catalog.CatalogManager;

/**
 *
 * @author 34667
 */
public class VistaPrincipal extends javax.swing.JFrame {

    private ControlaPuntos controlaPuntos;
    private Graphics graficos;
    private ArrayList<Punto> lPuntos;

    public VistaPrincipal(ControlaPuntos controlaPuntos) {
        this.controlaPuntos = controlaPuntos;
        initComponents();
        graficos = jPanelPuntos.getGraphics();
        jPanelPuntos.paintComponents(graficos);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPuntos = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        buttonGenerarPuntos = new javax.swing.JButton();
        buttonSalir = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        textNumPuntos = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        buttonAbrirMenuFicheros = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaMensajes = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        buttonGenerarFichero = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        buttonDibuja = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jComboAlgoritmos = new javax.swing.JComboBox<>();
        jButtonCalculaDistancia = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1050, 750));
        setPreferredSize(new java.awt.Dimension(1050, 750));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelPuntos.setBackground(new java.awt.Color(255, 255, 255));
        jPanelPuntos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        javax.swing.GroupLayout jPanelPuntosLayout = new javax.swing.GroupLayout(jPanelPuntos);
        jPanelPuntos.setLayout(jPanelPuntosLayout);
        jPanelPuntosLayout.setHorizontalGroup(
            jPanelPuntosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 646, Short.MAX_VALUE)
        );
        jPanelPuntosLayout.setVerticalGroup(
            jPanelPuntosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 526, Short.MAX_VALUE)
        );

        getContentPane().add(jPanelPuntos, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, 650, 530));

        jLabel1.setText("Indica el número de puntos aleatorios ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        buttonGenerarPuntos.setText("Generar");
        buttonGenerarPuntos.setActionCommand("GenerarPuntos");
        buttonGenerarPuntos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGenerarPuntosActionPerformed(evt);
            }
        });
        getContentPane().add(buttonGenerarPuntos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        buttonSalir.setText("Salir");
        buttonSalir.setActionCommand("SalirPrincipal");
        buttonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSalirActionPerformed(evt);
            }
        });
        getContentPane().add(buttonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 710, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 230, 10));
        getContentPane().add(textNumPuntos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 160, -1));

        jLabel3.setText("Generar desde fichero");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        buttonAbrirMenuFicheros.setText("Abrir");
        buttonAbrirMenuFicheros.setActionCommand("GenerarFichero");
        buttonAbrirMenuFicheros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAbrirMenuFicherosActionPerformed(evt);
            }
        });
        getContentPane().add(buttonAbrirMenuFicheros, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 230, 10));

        textAreaMensajes.setColumns(20);
        textAreaMensajes.setRows(5);
        jScrollPane1.setViewportView(textAreaMensajes);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 550, 530, 150));

        jLabel2.setText("Mensajes:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 550, -1, -1));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 570, 230, 10));

        jLabel4.setText("Generar fichero con valores aleatorios");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, -1, -1));

        jLabel5.setText("Elije algoritmo para calcular distancia mínima");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, -1, -1));

        buttonGenerarFichero.setText("Generar");
        buttonGenerarFichero.setActionCommand("GenerarFichero");
        buttonGenerarFichero.setHideActionText(true);
        getContentPane().add(buttonGenerarFichero, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, -1, -1));
        getContentPane().add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 230, 10));

        buttonDibuja.setText("Dibuja");
        buttonDibuja.setActionCommand("DibujaGraphics");
        getContentPane().add(buttonDibuja, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 640, -1, -1));
        getContentPane().add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 690, 230, 10));

        jLabel6.setText("Dibujar gráficas");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 600, -1, -1));

        jComboAlgoritmos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Exhaustivo" }));
        getContentPane().add(jComboAlgoritmos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, -1, -1));

        jButtonCalculaDistancia.setText("Calcula");
        jButtonCalculaDistancia.setActionCommand("calculaDistancia");
        jButtonCalculaDistancia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCalculaDistanciaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCalculaDistancia, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 530, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonGenerarPuntosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGenerarPuntosActionPerformed
        if (textNumPuntos.getText().isBlank() || Integer.parseInt(textNumPuntos.getText()) < 0 || Integer.parseInt(textNumPuntos.getText()) > 10000) { // controlar que sean solo numeros enteros
            System.out.println("Error: pon una cantidad de puntos entre 0-10000");
        } else {
            lPuntos = controlaPuntos.generaPuntosAleatorios(Integer.parseInt(textNumPuntos.getText()), 10,
                    jPanelPuntos.getWidth() - 10, 10, jPanelPuntos.getHeight() - 10);

            representaPuntos();

        }

    }//GEN-LAST:event_buttonGenerarPuntosActionPerformed


    private void buttonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSalirActionPerformed
        dispose();
    }//GEN-LAST:event_buttonSalirActionPerformed

    private void buttonAbrirMenuFicherosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAbrirMenuFicherosActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        int seleccion = fileChooser.showOpenDialog(this);

        if (seleccion == JFileChooser.APPROVE_OPTION) {
            try {
                lPuntos = controlaPuntos.generaPuntosFichero(fileChooser.getSelectedFile().getPath());
                lPuntos = controlaPuntos.factorConversion(lPuntos, jPanelPuntos.getWidth(), jPanelPuntos.getHeight());
                representaPuntos();
            } catch (Exception ex) {
                System.out.println("Error con el generaPuntosFichero: " + ex.getMessage());
            }
        }
    }//GEN-LAST:event_buttonAbrirMenuFicherosActionPerformed

    private void jButtonCalculaDistanciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalculaDistanciaActionPerformed
        controlaPuntos.exhaustivo(lPuntos);
    }//GEN-LAST:event_jButtonCalculaDistanciaActionPerformed

    private void representaPuntos() {

        graficos.drawLine(0, jPanelPuntos.getHeight() / 2, jPanelPuntos.getWidth(), jPanelPuntos.getHeight() / 2);
        graficos.drawLine(jPanelPuntos.getWidth() / 2, 0, jPanelPuntos.getWidth() / 2, jPanelPuntos.getHeight());
        graficos.drawLine(jPanelPuntos.getWidth() / 2, 0, jPanelPuntos.getWidth() / 2, jPanelPuntos.getHeight());
        Font f = new Font("Serif", Font.BOLD, 12);
        graficos.setFont(f);
        graficos.drawString("X", jPanelPuntos.getWidth() - 15, (jPanelPuntos.getHeight() / 2) - 5);
        graficos.drawString("Y", (jPanelPuntos.getWidth() / 2) + 5, 15);
        for (Punto punto : lPuntos) {
            graficos.drawOval((int) punto.getX(), (int) punto.getY(), 7, 7);
            graficos.fillOval((int) punto.getX(), (int) punto.getY(), 7, 7);
        }
    }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton buttonAbrirMenuFicheros;
    public javax.swing.JButton buttonDibuja;
    public javax.swing.JButton buttonGenerarFichero;
    public javax.swing.JButton buttonGenerarPuntos;
    public javax.swing.JButton buttonSalir;
    public javax.swing.JButton jButtonCalculaDistancia;
    public javax.swing.JComboBox<String> jComboAlgoritmos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    public javax.swing.JPanel jPanelPuntos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    public javax.swing.JTextArea textAreaMensajes;
    public javax.swing.JTextField textNumPuntos;
    // End of variables declaration//GEN-END:variables

}
