/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Vistas;

import Controlador.ControlaPuntos;
import javax.swing.JOptionPane;

/**
 *
 * @author israel
 */
public class VistaFicheroAleatorio extends javax.swing.JDialog {

    /**
     * Creates new form VistaFicheroAleatorio
     */
    private ControlaPuntos cp;
    public VistaFicheroAleatorio(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        cp = new ControlaPuntos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButtonCancelarFichero = new javax.swing.JButton();
        jTextNombreFichero = new javax.swing.JTextField();
        jTextCantidadPuntos = new javax.swing.JTextField();
        jButtonCrearFichero = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextRangoMin = new javax.swing.JTextField();
        jTextRangoMax = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Indica cantidad de puntos:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        jLabel2.setText("Indica nombre del archivo:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jButtonCancelarFichero.setText("Cancelar");
        jButtonCancelarFichero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarFicheroActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCancelarFichero, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 260, -1, -1));

        jTextNombreFichero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNombreFicheroActionPerformed(evt);
            }
        });
        getContentPane().add(jTextNombreFichero, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 130, -1));
        getContentPane().add(jTextCantidadPuntos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 130, -1));

        jButtonCrearFichero.setText("Crear");
        jButtonCrearFichero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCrearFicheroActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCrearFichero, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, -1, -1));

        jLabel3.setText("Máximo:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, -1, -1));

        jLabel4.setText("Rango puntos:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, -1, -1));

        jLabel5.setText("Mínimo:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, -1, -1));
        getContentPane().add(jTextRangoMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, -1, -1));
        getContentPane().add(jTextRangoMax, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextNombreFicheroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNombreFicheroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNombreFicheroActionPerformed

    private void jButtonCancelarFicheroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarFicheroActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonCancelarFicheroActionPerformed

    private void jButtonCrearFicheroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCrearFicheroActionPerformed
        if (Integer.parseInt(jTextCantidadPuntos.getText()) <= 0 || Integer.parseInt(jTextCantidadPuntos.getText()) >= 1999 || jTextCantidadPuntos.getText().isBlank()
                || jTextNombreFichero.getText().isBlank() || jTextRangoMax.getText().isBlank() || jTextRangoMin.getText().isBlank()) {
            JOptionPane.showConfirmDialog(this, "Error: Hay algún campo erroneo en la petición de datos", "ERROR", JOptionPane.ERROR_MESSAGE);
        } else {
           cp.generaFichero(Integer.parseInt(jTextCantidadPuntos.getText()), jTextNombreFichero.getText(), Double.parseDouble(jTextRangoMin.getText()),
                   Double.parseDouble(jTextRangoMax.getText()));
        }
    }//GEN-LAST:event_jButtonCrearFicheroActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButtonCancelarFichero;
    public javax.swing.JButton jButtonCrearFichero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    public javax.swing.JTextField jTextCantidadPuntos;
    public javax.swing.JTextField jTextNombreFichero;
    public javax.swing.JTextField jTextRangoMax;
    public javax.swing.JTextField jTextRangoMin;
    // End of variables declaration//GEN-END:variables
}
