/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import Controlador.ControlaPuntos;
import Modelo.Algoritmos;
import Modelo.ParPuntos;
import Modelo.Punto;
import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.io.File;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.xml.catalog.CatalogManager;

/**
 *
 * @author 34667
 */
public class VistaPrincipal extends javax.swing.JFrame {

    private ControlaPuntos controlaPuntos;
    private Graphics graficos;
    private ArrayList<Punto> lPuntos;
    private Algoritmos algoritmos;
    private ParPuntos cercanos;

    public VistaPrincipal(ControlaPuntos controlaPuntos) {
        this.controlaPuntos = controlaPuntos;
        this.algoritmos = new Algoritmos();
        initComponents();
        graficos = jPanelPuntos.getGraphics();
        jPanelPuntos.paintComponents(graficos);
//        for (Algoritmos.AlgoritmosEnum eAlgoritmos : Algoritmos.AlgoritmosEnum.values()) {
//            jComboAlgoritmos.addItem(eAlgoritmos.name());
//        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPuntos = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        buttonGenerarPuntos = new javax.swing.JButton();
        buttonSalir = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        textNumPuntos = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        buttonAbrirMenuFicheros = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaMensajes = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        buttonGenerarFichero = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        buttonDibuja = new javax.swing.JButton();
        jButtonCalcula = new javax.swing.JButton();
        jComboAlgoritmos = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1050, 750));
        setPreferredSize(new java.awt.Dimension(1050, 850));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelPuntos.setBackground(new java.awt.Color(255, 255, 255));
        jPanelPuntos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        javax.swing.GroupLayout jPanelPuntosLayout = new javax.swing.GroupLayout(jPanelPuntos);
        jPanelPuntos.setLayout(jPanelPuntosLayout);
        jPanelPuntosLayout.setHorizontalGroup(
            jPanelPuntosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanelPuntosLayout.setVerticalGroup(
            jPanelPuntosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(jPanelPuntos, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 650, 530));

        jLabel1.setText("Indica el número de puntos aleatorios ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        buttonGenerarPuntos.setText("Generar");
        buttonGenerarPuntos.setActionCommand("GenerarPuntos");
        buttonGenerarPuntos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGenerarPuntosActionPerformed(evt);
            }
        });
        getContentPane().add(buttonGenerarPuntos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        buttonSalir.setText("Salir");
        buttonSalir.setActionCommand("SalirPrincipal");
        buttonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSalirActionPerformed(evt);
            }
        });
        getContentPane().add(buttonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 710, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 230, 10));
        getContentPane().add(textNumPuntos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 160, -1));

        jLabel3.setText("Generar desde fichero");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        buttonAbrirMenuFicheros.setText("Abrir");
        buttonAbrirMenuFicheros.setActionCommand("GenerarFichero");
        buttonAbrirMenuFicheros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAbrirMenuFicherosActionPerformed(evt);
            }
        });
        getContentPane().add(buttonAbrirMenuFicheros, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 230, 10));

        textAreaMensajes.setColumns(20);
        textAreaMensajes.setRows(5);
        jScrollPane1.setViewportView(textAreaMensajes);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 580, 530, 150));

        jLabel2.setText("Mensajes:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 560, -1, -1));

        jLabel4.setText("Generar fichero con valores aleatorios");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, -1, -1));

        jLabel5.setText("Dibujar gráficas");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 580, -1, 20));

        buttonGenerarFichero.setText("Generar");
        buttonGenerarFichero.setActionCommand("GenerarFichero");
        buttonGenerarFichero.setHideActionText(true);
        buttonGenerarFichero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGenerarFicheroActionPerformed(evt);
            }
        });
        getContentPane().add(buttonGenerarFichero, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 520, -1, -1));
        getContentPane().add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 560, 230, 10));

        buttonDibuja.setText("Dibuja");
        buttonDibuja.setActionCommand("DibujaGraphics");
        buttonDibuja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDibujaActionPerformed(evt);
            }
        });
        getContentPane().add(buttonDibuja, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 620, -1, 20));

        jButtonCalcula.setText("Calcula");
        jButtonCalcula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCalculaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCalcula, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, -1, -1));

        jComboAlgoritmos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboAlgoritmosActionPerformed(evt);
            }
        });
        getContentPane().add(jComboAlgoritmos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 150, -1));

        jLabel6.setText("Elige un algoritmo:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));
        getContentPane().add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 670, 230, 10));
        getContentPane().add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 230, 10));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonGenerarPuntosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGenerarPuntosActionPerformed
        if (textNumPuntos.getText().isBlank() || Integer.parseInt(textNumPuntos.getText()) < 0 || Integer.parseInt(textNumPuntos.getText()) > 10000) { // controlar que sean solo numeros enteros
            System.out.println("Error: pon una cantidad de puntos entre 0-10000");
        } else {
            lPuntos = controlaPuntos.generaPuntosAleatorios(Integer.parseInt(textNumPuntos.getText()), 10,
                    jPanelPuntos.getWidth() - 10, 10, jPanelPuntos.getHeight() - 10);

            representaPuntos();
        }
    }//GEN-LAST:event_buttonGenerarPuntosActionPerformed


    private void buttonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSalirActionPerformed
        dispose();
    }//GEN-LAST:event_buttonSalirActionPerformed

    private void buttonAbrirMenuFicherosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAbrirMenuFicherosActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        int seleccion = fileChooser.showOpenDialog(this);

        if (seleccion == JFileChooser.APPROVE_OPTION) {
            try {
                lPuntos = controlaPuntos.generaPuntosFichero(fileChooser.getSelectedFile().getPath());
                lPuntos = controlaPuntos.factorConversion(lPuntos, jPanelPuntos.getWidth(), jPanelPuntos.getHeight());
                representaPuntos();
            } catch (Exception ex) {
                System.out.println("Error con el generaPuntosFichero: " + ex.getMessage());
            }
        }
    }//GEN-LAST:event_buttonAbrirMenuFicherosActionPerformed

    private void buttonDibujaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDibujaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonDibujaActionPerformed

    private void jComboAlgoritmosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboAlgoritmosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboAlgoritmosActionPerformed

    private void jButtonCalculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalculaActionPerformed
//        switch (jComboAlgoritmos.getSelectedIndex()) {
//            case Algoritmos.AlgoritmosEnum.EXHAUSTIVO.name():
//                cercanos = algoritmos.exhaustivo(lPuntos);
//
//                break;
//            case Algoritmos.AlgoritmosEnum.PODA.name():
//                cercanos = algoritmos.poda(lPuntos);// AQUI TE QUEDASTE ISRA, HAY QUE IMPLEMTNARLO Y VER LOS ERRORES
//                break;
//            case Algoritmos.AlgoritmosEnum.DIVIDEYVENCERAS.name():
//                break;
//        }
//        representaLineaMasCercanos();
    }//GEN-LAST:event_jButtonCalculaActionPerformed

    private void buttonGenerarFicheroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGenerarFicheroActionPerformed


    }//GEN-LAST:event_buttonGenerarFicheroActionPerformed
 CLASE CONTROLA GRAFICOS O CANVAS PRINCIPAL QUE HAGA ESTAS FUNCIONES PERO QUE VAYA INSTANCIANDO LOS OBJETOS PARA HACER REPAINT Y ESO
    private void representaLineaMasCercanos() {
        graficos.setColor(Color.red);
        graficos.drawLine((int) cercanos.getA().getX(), (int) cercanos.getA().getY(), (int) cercanos.getB().getX(), (int) cercanos.getB().getY());
        graficos.setColor(Color.black);
    }

    private void representaPuntos() {
        
        graficos.drawLine(0, jPanelPuntos.getHeight() / 2, jPanelPuntos.getWidth(), jPanelPuntos.getHeight() / 2);
        graficos.drawLine(jPanelPuntos.getWidth() / 2, 0, jPanelPuntos.getWidth() / 2, jPanelPuntos.getHeight());
        graficos.drawLine(jPanelPuntos.getWidth() / 2, 0, jPanelPuntos.getWidth() / 2, jPanelPuntos.getHeight());
        Font f = new Font("Serif", Font.BOLD, 12);
        graficos.setFont(f);
        graficos.drawString("X", jPanelPuntos.getWidth() - 15, (jPanelPuntos.getHeight() / 2) - 5);
        graficos.drawString("Y", (jPanelPuntos.getWidth() / 2) + 5, 15);
        for (Punto punto : lPuntos) {
            graficos.drawOval((int) punto.getX(), (int) punto.getY(), 7, 7);
            graficos.fillOval((int) punto.getX(), (int) punto.getY(), 7, 7);
        }
    }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton buttonAbrirMenuFicheros;
    public javax.swing.JButton buttonDibuja;
    public javax.swing.JButton buttonGenerarFichero;
    public javax.swing.JButton buttonGenerarPuntos;
    public javax.swing.JButton buttonSalir;
    public javax.swing.JButton jButtonCalcula;
    public javax.swing.JComboBox<String> jComboAlgoritmos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    public javax.swing.JPanel jPanelPuntos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    public javax.swing.JTextArea textAreaMensajes;
    public javax.swing.JTextField textNumPuntos;
    // End of variables declaration//GEN-END:variables

}
