/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

/**
 *
 * @author 34667
 */
public class VistaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VistaPrincipal
     */
    public VistaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPanelPuntos = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ButtonGenerarPuntos = new javax.swing.JButton();
        ButtonSalir = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        TextNumPuntos = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        AbrirMenuFicheros = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JPanelPuntos.setBackground(new java.awt.Color(255, 255, 255));
        JPanelPuntos.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));

        javax.swing.GroupLayout JPanelPuntosLayout = new javax.swing.GroupLayout(JPanelPuntos);
        JPanelPuntos.setLayout(JPanelPuntosLayout);
        JPanelPuntosLayout.setHorizontalGroup(
            JPanelPuntosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );
        JPanelPuntosLayout.setVerticalGroup(
            JPanelPuntosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
        );

        getContentPane().add(JPanelPuntos, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 430, 400));

        jLabel1.setText("Indica el número de puntos ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        ButtonGenerarPuntos.setText("Generar");
        ButtonGenerarPuntos.setActionCommand("GenerarPuntos");
        getContentPane().add(ButtonGenerarPuntos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        ButtonSalir.setText("Salir");
        ButtonSalir.setActionCommand("SalirPrincipal");
        getContentPane().add(ButtonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 220, 10));
        getContentPane().add(TextNumPuntos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 160, -1));

        jLabel3.setText("Generar desde fichero");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        AbrirMenuFicheros.setText("Abrir");
        AbrirMenuFicheros.setActionCommand("GenerarFichero");
        getContentPane().add(AbrirMenuFicheros, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 220, 10));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton AbrirMenuFicheros;
    public javax.swing.JButton ButtonGenerarPuntos;
    public javax.swing.JButton ButtonSalir;
    public javax.swing.JPanel JPanelPuntos;
    public javax.swing.JTextField TextNumPuntos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
