/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "GestorJuegos.h"

//El menu en el cliente y las operaciones en el servidor

/*
1.- Juego Nuevo. Esta opción es la primera que se debe ejecutarse y creará un sudoku con una
prioridad solicitada previamente por pantalla.
2.- Borrar Juego. Esta opción elimina el juego actual en el servidor, para ello se solicitará
previamente una confirmación para realizar la operación.
3.- Poner un valor. Solicitará la fila, columna y valor a poner en el tablero. Si ocurre cualquier
situación anómala o errónea mostrará un aviso en la línea de avisos de la aplicación.
4.- Borrar un valor. Solicitará la fila y la columna del tablero a eliminar. Si ocurre cualquier
error mostrará un aviso en la línea de avisos de la aplicación.
5.- Ayuda. Pedirá la fila y la columna del tablero y mostrará en la línea de avisos el conjunto de
posibles valores que pueden ponerse en dicha posición del tablero.
6.- Salir. Desconecta el cliente del servidor. Si se está jugando un partida preguntará si desea
eliminar el juego del servidor. Si se confirma borrará el juego mostrando un mensaje de la
operación y no se confirma mostrará un mensaje
*/
int * 
nuevo_1_svc(TDificultad *argp, struct svc_req *rqstp) //crea un sudoku pidiendo la dificultad y devuelve su codigo
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

bool_t *
borrar_1_svc(int *argp, struct svc_req *rqstp) //borra el juego actual
{
	static bool_t  result;

	/*
	 * insert server code here
	 */

	return &result;
}

bool_t *
ponervalor_1_svc(TFCV *argp, struct svc_req *rqstp) //Pone un valor en el tablero, devuelve true si lo ha hecho o false si no ha podido
{
	static bool_t  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
obtenervalor_1_svc(TFC *argp, struct svc_req *rqstp) //Pide fila y columna y devuelve el valor que almacena en esa posicion
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

bool_t *
comprobarvalor_1_svc(TFCV *argp, struct svc_req *rqstp) //Devuelve true si es un valor bueno en el tablero
{
	static bool_t  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
numerohuecos_1_svc(int *argp, struct svc_req *rqstp) //Devuelve el numero de huecos que quedan
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

bool_t *
correcto_1_svc(int *argp, struct svc_req *rqstp) //Devuelve true si el sudoku esta correcto
{
	static bool_t  result;

	/*
	 * insert server code here
	 */

	return &result;
}

void *
ayuda_1_svc(TFC *argp, struct svc_req *rqstp) //Coloca una ayuda en el tablero
{
	static char * result;

	/*
	 * insert server code here
	 */

	return (void *) &result;
}

RCadena *
getsudoku_1_svc(int *argp, struct svc_req *rqstp)//Devuelve una copia del sudoku
{
	static RCadena  result;

	/*
	 * insert server code here
	 */

	return &result;
}
