/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/AWTForms/Frame.java to edit this template
 */
package Vista;

import Controlador.CanvasCentroMasajes;
import Controlador.Centro;
import Modelo.ClienteMasaje;
import Modelo.ClienteRehabilita;
import java.awt.Color;
import static java.lang.Thread.sleep;
import java.util.ArrayList;
import java.util.Random;

/**
 *
 * @author 34667
 */
public class FrameCentroMasajes extends java.awt.Frame {

    /**
     * Creates new form FrameCentroMasajes
     */
    public FrameCentroMasajes() {

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        final int alto = 950, ancho = 650;
        Random r = new Random(System.nanoTime());
        ArrayList<Thread> lClientes = new ArrayList<>();
//        ArrayList<ClienteMasaje> lMasaje = new ArrayList<>();
//        ArrayList<ClienteRehabilita> lRehabilita = new ArrayList<>();
        CanvasCentroMasajes canvas = new CanvasCentroMasajes(alto, ancho, lClientes);//, lMasaje, lRehabilita);
        Centro recurso = new Centro(canvas);
        FrameCentroMasajes vCentro = new FrameCentroMasajes();

        vCentro.setSize(alto, ancho);

        vCentro.setResizable(
                false);

        vCentro.setTitle(
                "Práctica 5 Israel Fargas"
                + "");
        vCentro.setBackground(Color.LIGHT_GRAY);

        vCentro.add(canvas);

        vCentro.setVisible(
                true);

        try {

            for (int i = 0;
                    i < 10; i++) {

                if (r.nextInt(1, 101) > 60) { //genera un clienteMasaje
                    ClienteMasaje masajeTemp = new ClienteMasaje(recurso);
                    //lMasaje.add(masajeTemp);
                    lClientes.add(masajeTemp);
                } else { //genera un clienteRehabilita
                    ClienteRehabilita rehabilitaTmp = new ClienteRehabilita(recurso);
                    lClientes.add(new Thread(rehabilitaTmp));
                    //lRehabilita.add(rehabilitaTmp);
                }
                sleep(200 / r.nextInt(1, 3));
            }
            for (Thread cliente : lClientes) {
                cliente.join();
            }
        } catch (InterruptedException ex) {
            System.out.println("Error con los sleeps o con los join: " + ex.getMessage());
        }

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
