/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/AWTForms/Frame.java to edit this template
 */
package Vista;

import Controlador.CanvasPerrosGatos;
import Modelo.Comedero;
import Modelo.Gato;
import Modelo.Perro;
import java.time.Duration;
import java.util.ArrayList;
import java.util.Random;

/**
 *
 * @author 34667
 */
public class VistaPerrosGatos extends java.awt.Frame {

//    public class ColaPerro {
//
//        private int numElementos;
//        ArrayList<Perro> cola;
//
//        public ColaPerro() {
//            numElementos = 0;
//            cola = new ArrayList<>();
//        }
//
//        public void acolar(Perro a) {
//            cola.add(a);
//        }
//
//        public Perro desacolar() {
//            
//            if(!esVacia()){
//            numElementos--;
//            return cola.get(0);
//            }
//            return null;
//        }
//
//        public boolean esVacia() {
//            return numElementos == 0;
//        }
//    }
//    
//     public class ColaGato {
//
//        private int numElementos;
//        ArrayList<Gato> cola;
//
//        public ColaGato() {
//            numElementos = 0;
//            cola = new ArrayList<>();
//        }
//
//        public void acolar(Gato a) {
//            cola.add(a);
//        }
//
//        public Gato desacolar() {
//            
//            if(!esVacia()){
//            numElementos--;
//            return cola.get(0);
//            }
//            return null;
//        }
//
//        public boolean esVacia() {
//            return numElementos == 0;
//        }
//    }
    /**
     * Creates new form VistaPerrosGatos
     */
    public VistaPerrosGatos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            VistaPerrosGatos f = new VistaPerrosGatos();
            Random rand = new Random(System.nanoTime());
            Thread animales[] = new Thread[20];
            Comedero comedero = new Comedero();

            f.setSize(1000, 1000);
            CanvasPerrosGatos cv = new CanvasPerrosGatos(1000, 1000);
            f.add(cv);
            f.setVisible(true);

            for (int i = 0; i < 20; i++) {
                if (rand.nextBoolean()) {
                    animales[i] = new Perro(cv, comedero);
                } else {
                    animales[i] = new Thread(new Gato(comedero, cv));
                }
                animales[i].start();
                Thread.sleep(Duration.ofSeconds(rand.nextInt(1, 3)));

            }
            for (int i = 0; i < 20; i++) {
                animales[i].join();
            }
            System.out.println("Ha terminado el programa");
            Thread.sleep(Duration.ofSeconds(5));

        } catch (Exception e) {
            System.out.println("Error fatal en el generador: " + e.getMessage());
        } finally {
            System.exit(0);
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
