/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "GestorBiblioteca.h"


bool_t hayAdmin = FALSE;
int idAdmin;
Cadena contraseñaAdmin = {1,2,3,4};

int nLibros =0;
TLibro *libros = NULL;
FILE *fDatos = NULL;

int *
conexion_1_svc(char *argp, struct svc_req *rqstp)
{
	static int  result;

	if(!hayAdmin){
		printf("\n Entro porque no hay admin logeado");
		printf("\nArgp = %c\n*Argp = %c",argp,*argp);
		if(strcmp(contraseñaAdmin,*argp) == 0){
			hayAdmin = TRUE;
			idAdmin = 1+rand()%RAND_MAX;
			printf("\nLog exitoso, el idGenerado es %d",idAdmin);
		}else{
			printf("\nLa contraseña era incorrecta, error");
			idAdmin = -2;
		}
	}else{
		printf("\nYa hay un admin online");
		idAdmin = -1;
	}

	result = idAdmin;

	return &result;
}

bool_t *
desconexion_1_svc(int *argp, struct svc_req *rqstp)
{
	static bool_t  result;

	if(*argp == idAdmin){
		result = TRUE;
	}else{
		result = FALSE;
	}
	
	return &result;
}

int *
cargardatos_1_svc(TConsulta *argp, struct svc_req *rqstp)
{
	static int  result;

	if(!hayAdmin || (hayAdmin && (strcmp(argp->Ida,idAdmin)==0))){

		AQUI TE QUEDASTE ISRA, TIENES QUE COMPROBAR SI EL FICHERO YA HA SIDO ABIERTO Y TAL

	}else{
		result = -1;
	}

	return &result;
}

bool_t *
guardardatos_1_svc(int *argp, struct svc_req *rqstp)
{
	static bool_t  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
nuevolibro_1_svc(TNuevo *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
comprar_1_svc(TComRet *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
retirar_1_svc(TComRet *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

bool_t *
ordenar_1_svc(TOrdenacion *argp, struct svc_req *rqstp)
{
	static bool_t  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
nlibros_1_svc(int *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
buscar_1_svc(TConsulta *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

TLibro *
descargar_1_svc(TPosicion *argp, struct svc_req *rqstp)
{
	static TLibro  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
prestar_1_svc(TPosicion *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
devolver_1_svc(TPosicion *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}
