/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Modelo.ParDePuntos;
import Modelo.Punto;
import java.awt.Color;
import java.awt.Graphics;
import java.util.ArrayList;

/**
 *
 * @author marin
 */
public class VistaPuntosFichero extends javax.swing.JFrame {

    /**
     * Creates new form VistaPuntosAleatorios
     */
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
    private ArrayList<Punto> puntos;
    private ParDePuntos puntosCercanos;
    private int TamPuntos = 5, TamMult = 1;


    public VistaPuntosFichero() {
        initComponents();
        puntos = new ArrayList<>();
        

    }

    public ParDePuntos getPuntosCercanos() {
        return puntosCercanos;
    }

    public void setPuntosCercanos(ParDePuntos puntosCercanos) {
        this.puntosCercanos = puntosCercanos;
    }

    public ArrayList<Punto> getPuntos() {
        return puntos;
    }

    public void setPuntos(ArrayList<Punto> puntos) {
        this.puntos = puntos;

    }

    /**
     *
     * @param g
     */
    @Override
    public void paint(Graphics g) {

        super.paint(g);
        //g=PanelPuntos.getGraphics();
        
        g = this.JPanelFicheros.getGraphics();
        int minX = Integer.MAX_VALUE, minY = Integer.MAX_VALUE, maxX = Integer.MIN_VALUE, maxY = Integer.MIN_VALUE;
        int panelWidth = JPanelFicheros.getWidth();
        int panelHeight = JPanelFicheros.getHeight();
        ArrayList<Punto> puntosRescalados = new ArrayList<>();

        if (!puntos.isEmpty()) {

            for (Punto p : puntos) {

                minX = (int) Math.min(minX, p.getX());
                maxX = (int) Math.max(maxX, p.getX());
                minY = (int) Math.min(minY, p.getY());
                maxY = (int) Math.max(maxY, p.getY());

                //g.fillOval((int)p.getX()*TamMult,(int) p.getY()*TamMult, TamPuntos,TamPuntos);
            }
            int rangeX = maxX - minX;
            int rangeY = maxY - minY;
            int buffer = 20;
            double scaleX = (panelWidth - buffer) / (maxX - minX);
            double scaleY = (panelHeight - buffer) / (maxY - minY);
            double scale = Math.min(scaleX, scaleY);

            //Dibujamos los puntos escalados
            double x;
            double y;
            for (Punto p : puntos) {

                x = (p.getX() - minX) / rangeX * (panelWidth-buffer);
                y = (p.getY() - minY) / rangeY * (panelHeight-buffer);

                g.fillOval((int) x, (int) y, TamPuntos, TamPuntos);

            }

            //Dibujamos puntos mas cercanos
            double punto1X = (puntosCercanos.getA().getX() - minX) / rangeX * (panelWidth-buffer);
            double punto1Y = (puntosCercanos.getA().getY() - minY) / rangeY * (panelHeight-buffer);

            double punto2X = (puntosCercanos.getB().getX() - minX) / rangeX * (panelWidth-buffer);
            double punto2Y = (puntosCercanos.getB().getY() - minY) / rangeY * (panelHeight-buffer);

            //System.out.println("Tamaño pantalla: "+JPanelAleatorios.getWidth() +", "+JPanelAleatorios.getHeight()+"\nY los puntos son"+puntosCercanos.getA().getX()+" "+puntosCercanos.getA().getY()+" "+puntosCercanos.getB().getX()+" "+puntosCercanos.getB().getY());
            //System.out.println(punto1X+" "+punto1Y+" "+punto2X+" "+punto2Y);
            g.setColor(Color.red);

            g.drawLine((int) punto1X, (int) punto1Y, (int) punto2X, (int) punto2Y);
            g.fillOval((int)punto1X,(int)punto1Y, TamPuntos,TamPuntos);
            g.fillOval((int)punto2X,(int)punto2Y, TamPuntos,TamPuntos);
            g.setColor(Color.BLACK);

        }

    }

    public void pintaPuntos() {

        repaint();
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        ComboBoxFichero = new javax.swing.JComboBox<>();
        JPanelFicheros = new javax.swing.JPanel();
        BotonAnalizarFichero = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        TextSolPunto1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TextTiempo = new javax.swing.JTextField();
        BotonVolverAnalisisFichero = new javax.swing.JButton();
        CompararTodosfichero = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        TextSolPunto2 = new javax.swing.JTextField();
        BotonAbrirFichero = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Elige algoritmo");

        ComboBoxFichero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elige Algoritmo", "Exhaustivo", "Búsqueda con Poda", "DyV", "DyV mejorado", "Comparar todos" }));

        javax.swing.GroupLayout JPanelFicherosLayout = new javax.swing.GroupLayout(JPanelFicheros);
        JPanelFicheros.setLayout(JPanelFicherosLayout);
        JPanelFicherosLayout.setHorizontalGroup(
            JPanelFicherosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 834, Short.MAX_VALUE)
        );
        JPanelFicherosLayout.setVerticalGroup(
            JPanelFicherosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 634, Short.MAX_VALUE)
        );

        BotonAnalizarFichero.setText("Analizar");
        BotonAnalizarFichero.setActionCommand("AnalizarPorFichero");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 210, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 79, Short.MAX_VALUE)
        );

        jLabel3.setText("Solución");

        TextSolPunto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextSolPunto1ActionPerformed(evt);
            }
        });

        jLabel4.setText("Tiempo");

        BotonVolverAnalisisFichero.setText("Volver");
        BotonVolverAnalisisFichero.setActionCommand("VolverAnalisisFichero");

        CompararTodosfichero.setText("Comparar todas las estrategias");
        CompararTodosfichero.setActionCommand("Comparar todas las estrategias fichero");

        jLabel5.setText("Punto 2");

        jLabel6.setText("Punto 1");

        TextSolPunto2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextSolPunto2ActionPerformed(evt);
            }
        });

        BotonAbrirFichero.setText("Abrir fichero");
        BotonAbrirFichero.setActionCommand("Abrir fichero de Puntos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(JPanelFicheros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(BotonAbrirFichero)
                        .addGap(49, 49, 49)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ComboBoxFichero, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(BotonAnalizarFichero, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BotonVolverAnalisisFichero)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(TextSolPunto1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(TextSolPunto2, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(TextTiempo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CompararTodosfichero, javax.swing.GroupLayout.Alignment.LEADING))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(ComboBoxFichero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BotonAnalizarFichero)
                            .addComponent(BotonAbrirFichero)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JPanelFicheros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(25, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addGap(4, 4, 4)
                        .addComponent(TextSolPunto1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextSolPunto2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(CompararTodosfichero)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BotonVolverAnalisisFichero)
                        .addGap(60, 60, 60))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextSolPunto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextSolPunto1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextSolPunto1ActionPerformed

    private void TextSolPunto2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextSolPunto2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextSolPunto2ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton BotonAbrirFichero;
    public javax.swing.JButton BotonAnalizarFichero;
    public javax.swing.JButton BotonVolverAnalisisFichero;
    public javax.swing.JComboBox<String> ComboBoxFichero;
    public javax.swing.JButton CompararTodosfichero;
    public javax.swing.JPanel JPanelFicheros;
    public javax.swing.JTextField TextSolPunto1;
    public javax.swing.JTextField TextSolPunto2;
    public javax.swing.JTextField TextTiempo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
