/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author marin
 */
public class VistaEligeVoraz extends javax.swing.JFrame {

    /**
     * Creates new form VistaEligeVoraz
     */
    public VistaEligeVoraz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BotonUnidireccionalAleatorios = new javax.swing.JButton();
        BotonUnidireccionalFichero = new javax.swing.JButton();
        BotonVolverEligeVoraz = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        BotonBidireccionalAleatorios = new javax.swing.JButton();
        BotonBidireccionalFichero = new javax.swing.JButton();
        BotonCompararVoraces = new javax.swing.JButton();
        BotonAbrirFicheroCompararVoraces = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BotonUnidireccionalAleatorios.setText("Puntos Aleatorios");
        BotonUnidireccionalAleatorios.setToolTipText("");
        BotonUnidireccionalAleatorios.setActionCommand("Abrir Vista Aleatorios Unidireccional");

        BotonUnidireccionalFichero.setText("Abrir Fichero");
        BotonUnidireccionalFichero.setActionCommand("Abrir Vista Fichero Unidireccional");

        BotonVolverEligeVoraz.setText("Volver");
        BotonVolverEligeVoraz.setActionCommand("VolverEligeVoraz");

        jLabel1.setText("Unidireccional");

        jLabel2.setText("Bidireccional");

        BotonBidireccionalAleatorios.setText("Puntos Aleatorios");
        BotonBidireccionalAleatorios.setToolTipText("");
        BotonBidireccionalAleatorios.setActionCommand("Vista Aleatorios Bidireccional");

        BotonBidireccionalFichero.setText("Abrir Fichero");
        BotonBidireccionalFichero.setActionCommand("Abrir Vista Fichero Bidireccional");

        BotonCompararVoraces.setText("Comparar Unidireccional y bidireccional");
        BotonCompararVoraces.setActionCommand("Comparar Voraces");

        BotonAbrirFicheroCompararVoraces.setText("Abrir Fichero y comparar estrategias");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BotonVolverEligeVoraz)
                .addGap(27, 27, 27))
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BotonCompararVoraces)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(BotonBidireccionalAleatorios)
                            .addGap(18, 18, 18)
                            .addComponent(BotonBidireccionalFichero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(BotonUnidireccionalAleatorios)
                            .addGap(18, 18, 18)
                            .addComponent(BotonUnidireccionalFichero, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(BotonAbrirFicheroCompararVoraces, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonUnidireccionalAleatorios)
                    .addComponent(BotonUnidireccionalFichero))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(BotonBidireccionalAleatorios)
                    .addComponent(BotonBidireccionalFichero))
                .addGap(31, 31, 31)
                .addComponent(BotonCompararVoraces)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotonAbrirFicheroCompararVoraces)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(BotonVolverEligeVoraz)
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton BotonAbrirFicheroCompararVoraces;
    public javax.swing.JButton BotonBidireccionalAleatorios;
    public javax.swing.JButton BotonBidireccionalFichero;
    public javax.swing.JButton BotonCompararVoraces;
    public javax.swing.JButton BotonUnidireccionalAleatorios;
    public javax.swing.JButton BotonUnidireccionalFichero;
    public javax.swing.JButton BotonVolverEligeVoraz;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
