/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Modelo.ParDePuntos;
import Modelo.Punto;
import java.awt.Canvas;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import java.util.ArrayList;

/**
 *
 * @author marin
 */
public class VistaPuntosAleatorios extends javax.swing.JFrame{

    /**
     * Creates new form VistaPuntosAleatorios
     */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private ArrayList<Punto> puntos;
    private ParDePuntos puntosCercanos;
    private int TamPuntos = 5, TamMult = 1;
    private double px, py;

    public VistaPuntosAleatorios() {
        initComponents();
        puntos = new ArrayList<>();

    }

    public ParDePuntos getPuntosCercanos() {
        return puntosCercanos;
    }

    public void setPuntosCercanos(ParDePuntos puntosCercanos) {
        this.puntosCercanos = puntosCercanos;
    }

    public ArrayList<Punto> getPuntos() {
        return puntos;
    }

    public void setPuntos(ArrayList<Punto> puntos) {
        this.puntos = puntos;

    }
  
    /**
     *
     * @param g
     */
    @Override
    public void paint(Graphics g) {

        super.paint(g);
        //g=PanelPuntos.getGraphics();
        
        g = this.JPanelAleatorios.getGraphics();
        int minX = Integer.MAX_VALUE, minY = Integer.MAX_VALUE, maxX = Integer.MIN_VALUE, maxY = Integer.MIN_VALUE;
        int panelWidth = JPanelAleatorios.getWidth();
        int panelHeight = JPanelAleatorios.getHeight();
        ArrayList<Punto> puntosRescalados = new ArrayList<>();

        if (!puntos.isEmpty()) {

            for (Punto p : puntos) {

                minX = (int) Math.min(minX, p.getX());
                maxX = (int) Math.max(maxX, p.getX());
                minY = (int) Math.min(minY, p.getY());
                maxY = (int) Math.max(maxY, p.getY());

                //g.fillOval((int)p.getX()*TamMult,(int) p.getY()*TamMult, TamPuntos,TamPuntos);
            }
            int rangeX = maxX - minX;
            int rangeY = maxY - minY;
            int buffer = 20;
            double scaleX = (panelWidth - buffer) / (maxX - minX);
            double scaleY = (panelHeight - buffer) / (maxY - minY);
            double scale = Math.min(scaleX, scaleY);

            //Dibujamos los puntos escalados
            double x;
            double y;
            for (Punto p : puntos) {

                x = (p.getX() - minX) / rangeX * (panelWidth-buffer);
                y = (p.getY() - minY) / rangeY * (panelHeight-buffer);

                g.fillOval((int) x, (int) y, TamPuntos, TamPuntos);

            }

            //Dibujamos puntos mas cercanos
            double punto1X = (puntosCercanos.getA().getX() - minX) / rangeX * (panelWidth-buffer);
            double punto1Y = (puntosCercanos.getA().getY() - minY) / rangeY * (panelHeight-buffer);

            double punto2X = (puntosCercanos.getB().getX() - minX) / rangeX * (panelWidth-buffer);
            double punto2Y = (puntosCercanos.getB().getY() - minY) / rangeY * (panelHeight-buffer);

            //System.out.println("Tamaño pantalla: "+JPanelAleatorios.getWidth() +", "+JPanelAleatorios.getHeight()+"\nY los puntos son"+puntosCercanos.getA().getX()+" "+puntosCercanos.getA().getY()+" "+puntosCercanos.getB().getX()+" "+puntosCercanos.getB().getY());
            //System.out.println(punto1X+" "+punto1Y+" "+punto2X+" "+punto2Y);
            g.setColor(Color.red);

            g.drawLine((int) punto1X, (int) punto1Y, (int) punto2X, (int) punto2Y);
            g.fillOval((int)punto1X,(int)punto1Y, TamPuntos,TamPuntos);
            g.fillOval((int)punto2X,(int)punto2Y, TamPuntos,TamPuntos);
            g.setColor(Color.BLACK);

        }

    }

    public void pintaPuntos() {

        repaint();
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        ComboBoxAleatorio = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        TextNum = new javax.swing.JTextField();
        JPanelAleatorios = new javax.swing.JPanel();
        BotonGenerarAnalizarAleatorios = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        TextSolPunto1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TextTiempo = new javax.swing.JTextField();
        GuardarAleatoriosEnFichero = new javax.swing.JButton();
        BotonVolverAnalisisAleatorio = new javax.swing.JButton();
        CompararTodosAleatorios = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        TextSolPunto2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Elige algoritmo");

        ComboBoxAleatorio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elige Algoritmo", "Exhaustivo", "Búsqueda con Poda", "DyV", "DyV mejorado", "Comparar todos" }));

        jLabel1.setText("Nº puntos");

        TextNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextNumActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JPanelAleatoriosLayout = new javax.swing.GroupLayout(JPanelAleatorios);
        JPanelAleatorios.setLayout(JPanelAleatoriosLayout);
        JPanelAleatoriosLayout.setHorizontalGroup(
            JPanelAleatoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 834, Short.MAX_VALUE)
        );
        JPanelAleatoriosLayout.setVerticalGroup(
            JPanelAleatoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 634, Short.MAX_VALUE)
        );

        BotonGenerarAnalizarAleatorios.setText(" Generar y Analizar");
        BotonGenerarAnalizarAleatorios.setActionCommand("Generar y Analizar Aleatorios");

        jLabel3.setText("Solución");

        TextSolPunto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextSolPunto1ActionPerformed(evt);
            }
        });

        jLabel4.setText("Tiempo");

        GuardarAleatoriosEnFichero.setText("Guardar puntos en un fichero");

        BotonVolverAnalisisAleatorio.setText("Volver");
        BotonVolverAnalisisAleatorio.setActionCommand("Volver Analisis Puntos Aleatorios");

        CompararTodosAleatorios.setText("Comparar todas las estrategias");
        CompararTodosAleatorios.setActionCommand("Comparar todas las estrategias Aleatorios");

        jLabel5.setText("Punto 2");

        jLabel6.setText("Punto 1");

        TextSolPunto2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextSolPunto2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(JPanelAleatorios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(TextNum, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ComboBoxAleatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(BotonGenerarAnalizarAleatorios, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CompararTodosAleatorios)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(BotonVolverAnalisisAleatorio)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextSolPunto1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                            .addComponent(GuardarAleatoriosEnFichero, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextSolPunto2, javax.swing.GroupLayout.Alignment.LEADING))
                        .addComponent(TextTiempo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TextNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(ComboBoxAleatorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonGenerarAnalizarAleatorios, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JPanelAleatorios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(25, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addGap(4, 4, 4)
                        .addComponent(TextSolPunto1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextSolPunto2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74)
                        .addComponent(GuardarAleatoriosEnFichero)
                        .addGap(26, 26, 26)
                        .addComponent(CompararTodosAleatorios)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BotonVolverAnalisisAleatorio)
                        .addGap(60, 60, 60))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextNumActionPerformed

    private void TextSolPunto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextSolPunto1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextSolPunto1ActionPerformed

    private void TextSolPunto2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextSolPunto2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextSolPunto2ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton BotonGenerarAnalizarAleatorios;
    public javax.swing.JButton BotonVolverAnalisisAleatorio;
    public javax.swing.JComboBox<String> ComboBoxAleatorio;
    public javax.swing.JButton CompararTodosAleatorios;
    public javax.swing.JButton GuardarAleatoriosEnFichero;
    public javax.swing.JPanel JPanelAleatorios;
    public javax.swing.JTextField TextNum;
    public javax.swing.JTextField TextSolPunto1;
    public javax.swing.JTextField TextSolPunto2;
    public javax.swing.JTextField TextTiempo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
