package Servidor;


import static java.lang.Thread.sleep;
import java.util.Random;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/AWTForms/Frame.java to edit this template
 */

/**
 *
 * @author israel
 */
public class ElJamon extends java.awt.Frame {

    /**
     * Creates new form ElJamon
     */
    public ElJamon() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            int alto = 800;
            int ancho = 700;
            ElJamon vista = new ElJamon();
            CanvasTienda cv = new CanvasTienda(alto, ancho);
            Tienda t = new Tienda();
            Random rand = new Random(System.nanoTime());
            

            vista.setSize(ancho, alto);
            vista.setLocationRelativeTo(null);
            vista.add(cv);
            vista.setVisible(true);
            vista.setTitle("Práctica 9 Israel Fargas Asquith");

            //JOptionPane.showMessageDialog(null, "El tiempo total en pagar con tarjeta es: "+tiempoT+ "  El tiempo total en pagar con Efectivo es: "+tiempoE);


            System.out.println("Fin del programa, se queda congelado 50 seg");
            sleep(50000);

        } catch (Exception e) {
            System.out.println("Error fatal en main: " + e.getMessage());
        } finally {
            System.exit(0);
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
