/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author marin
 */
public class VistaDatosAFD extends javax.swing.JFrame {

    /**
     * Creates new form VistaDatosAFD
     */
    public VistaDatosAFD() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        TextNumNodosAFD = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TextSimbolosAFD = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TextEstadoInicialAFD = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TextEstadoFinalAFD = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        BotonAceptarDatosAFD = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextTransicionesAFD = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        TextCadena = new javax.swing.JTextField();
        BotonVolverDatosAFND = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Introduce el número de nodos");

        jLabel2.setText("Introduce símbolos");

        jLabel3.setText("Estado Inicial");

        TextEstadoInicialAFD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextEstadoInicialAFDActionPerformed(evt);
            }
        });

        jLabel4.setText("Estado Final");

        TextEstadoFinalAFD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextEstadoFinalAFDActionPerformed(evt);
            }
        });

        jLabel5.setText("Transiciones");

        BotonAceptarDatosAFD.setText("OK");
        BotonAceptarDatosAFD.setActionCommand("AceptarDatosAFD");
        BotonAceptarDatosAFD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAceptarDatosAFDActionPerformed(evt);
            }
        });

        TextTransicionesAFD.setColumns(20);
        TextTransicionesAFD.setRows(5);
        jScrollPane1.setViewportView(TextTransicionesAFD);

        jLabel6.setText("Introducir Cadena a comprobar");

        BotonVolverDatosAFND.setText("Volver");
        BotonVolverDatosAFND.setActionCommand("VolverDatosAFD");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(BotonVolverDatosAFND)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BotonAceptarDatosAFD)
                .addGap(45, 45, 45))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2)
                                .addComponent(jLabel4))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(jLabel5))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TextCadena, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(TextSimbolosAFD, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                        .addComponent(TextEstadoInicialAFD)
                        .addComponent(TextEstadoFinalAFD)
                        .addComponent(TextNumNodosAFD))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(174, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextNumNodosAFD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TextSimbolosAFD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextEstadoInicialAFD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(TextEstadoFinalAFD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel5)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextCadena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonAceptarDatosAFD, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonVolverDatosAFND))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextEstadoInicialAFDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextEstadoInicialAFDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextEstadoInicialAFDActionPerformed

    private void TextEstadoFinalAFDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextEstadoFinalAFDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextEstadoFinalAFDActionPerformed

    private void BotonAceptarDatosAFDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAceptarDatosAFDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonAceptarDatosAFDActionPerformed

 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton BotonAceptarDatosAFD;
    public javax.swing.JButton BotonVolverDatosAFND;
    public javax.swing.JTextField TextCadena;
    public javax.swing.JTextField TextEstadoFinalAFD;
    public javax.swing.JTextField TextEstadoInicialAFD;
    public javax.swing.JTextField TextNumNodosAFD;
    public javax.swing.JTextField TextSimbolosAFD;
    public javax.swing.JTextArea TextTransicionesAFD;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
