/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "GestorJuegos.h"


void
gestorjuegos_1(char *host)
{
	CLIENT *clnt;
	int  *result_1;
	TDificultad  nuevo_1_arg;
	bool_t  *result_2;
	int  borrar_1_arg;
	bool_t  *result_3;
	TFCV  ponervalor_1_arg;
	char  *result_4;
	TFC  obtenervalor_1_arg;
	bool_t  *result_5;
	TFCV  comprobarvalor_1_arg;
	int  *result_6;
	int  numerohuecos_1_arg;
	bool_t  *result_7;
	int  correcto_1_arg;
	RCadena  *result_8;
	TFC  ayuda_1_arg;
	RCadena  *result_9;
	int  getsudoku_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, GESTORJUEGOS, GESTORJUEGOS_VER, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = nuevo_1(&nuevo_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = borrar_1(&borrar_1_arg, clnt);
	if (result_2 == (bool_t *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_3 = ponervalor_1(&ponervalor_1_arg, clnt);
	if (result_3 == (bool_t *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_4 = obtenervalor_1(&obtenervalor_1_arg, clnt);
	if (result_4 == (char *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_5 = comprobarvalor_1(&comprobarvalor_1_arg, clnt);
	if (result_5 == (bool_t *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_6 = numerohuecos_1(&numerohuecos_1_arg, clnt);
	if (result_6 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_7 = correcto_1(&correcto_1_arg, clnt);
	if (result_7 == (bool_t *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_8 = ayuda_1(&ayuda_1_arg, clnt);
	if (result_8 == (RCadena *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_9 = getsudoku_1(&getsudoku_1_arg, clnt);
	if (result_9 == (RCadena *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	gestorjuegos_1 (host);
exit (0);
}
